spring:
  application:
    name: "ddd demo"
    description: "This is demo for ddd workshop"
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: 122333
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8000

swagger:
  protocol: http

api:
  version: v1