CREATE TABLE USER
(
  UUID      VARCHAR(255) NOT NULL,
  EMAIL     VARCHAR(255) NOT NULL,
  PASS_WORD VARCHAR(255),
  PRIMARY KEY (UUID)
);

CREATE TABLE POLICY
(
  POLICY_NUMBER          VARCHAR(255) NOT NULL,
  POLICY_HOLDER_BIRTHDAY VARCHAR(255),
  POLICY_HOLDER_EMAIL    VARCHAR(255),
  POLICY_HOLDER_ID       VARCHAR(255),
  POLICY_HOLDER_NAME     VARCHAR(255),
  QUOTE_ID               VARCHAR(255),
  START_DATE             VARCHAR(255),
  PRIMARY KEY (POLICY_NUMBER)
)